module.exports =

  so15:
    'jquery':     name: 'Yehuda Katz', me: 'wycats', claim: 'Rails Core Team Member'
    'ruby-on-rails':name: 'Yehuda Katz', me: 'wycats', claim: 'Rails Core Team Member'
    'python':     name: 'Martijn Pieters', me: 'zopatista', claim: 'All-time Python #1 Answerer'
    'laravel':    name: 'Antonio Carlos Ribeiro', me: 'antonioribeiro', claim: 'All-time Laravel #1 Answerer'
    'typescript': name: 'Basarat Ali', me: 'basarat', claim: 'Typescript Top Answerer'
    'uikit':      name: 'Nevan King', me: 'nevanking', claim: 'UIkit Top Answerer'
    'uilabel':    name: 'Nevan King', me: 'nevanking', claim: 'UIlabel Top Answerer'
    'cocoa-touch':name: 'Nevan King', me: 'nevanking', claim: 'Cocoa-touch Top Answerer'
    'scheme':     name: 'Chris K. Jester-Young', me: 'cky', claim: 'Scheme Top Answerer'
    'd3.js':      name: 'Lars Kotthoff', me: 'larskotthoff', claim: 'd3.js Top Answerer'
    'google-chrome':name: 'Todd Motto', me: 'toddmotto', claim: 'Google Chrome GDE'
    'ruby':       name: 'Yehuda Katz', me: 'wycats', claim: 'Rails Core Team Member'
    'android' :   name: 'Ran Nachmany', me: 'rannachmany', claim: 'Android Google Developer Expert'
    'angularjs':  name: 'Matias Niemelä', me: 'matsko', claim: 'AngularJS Core Team'
    'php':        name: 'Phil Sturgeon', me: 'philsturgeon', claim: 'PHP Top Answerer'
    'codeigniter':name: 'Phil Sturgeon', me: 'philsturgeon', claim: 'All-time CodeIgniter #1 Answerer'
    'node.js':    name: 'Tim Caswell', me: 'creationix', claim: 'Early Node.js Contributor'
    'nginx':      name: 'Aaron Bedra', me: 'abedra', claim: 'Early Node.js Contributor'
    'ios':        name: 'Wain Glaister', me: 'wain', claim: 'iOS Top Answerer'
    'django':     name: 'Daniel Roseman', me: 'danielroseman', claim: 'Django #1 Answerer'
    'ember.js':   name: 'Michael Grassotti', me: 'mikegrassotti', claim: 'All-time Ember.js #1 Answerer'
    'express':    name: 'Peter Lyson', me: 'focusaurus', claim: 'All-time Express #1 Answerer'
    'mysql':      name: 'Alex Bolenok', me: 'quassnoi', claim: 'All-time MySql Top Answerer'
    'twilio':     name: 'Jeff Linwood', me: 'jefflinwood', claim: 'Twilio book author'
    # 'asp.net':    name: 'Amir Rajan', me: 'amirrajan', claim: 'ASP .net AirPair Expert'
    # 'c++':        name: 'Steve Purves', me: 'stevejpurves', claim: 'C++ AirPair Expert'
    # 'java':       name: 'Marko Topolnik', me: 'marko', claim: 'Java Top Answerer'
    # 'c#':         name: 'John Feminella', me: 'john-feminella', claim: 'C# Top Answerer'


  so10:
    'ruby':       name: 'Yehuda Katz', me: 'wycats', claim: 'Rails Core Team Member'
    'python':     name: 'Daniel Roseman', me: 'danielroseman', claim: 'Django #1 Answerer'
    'android' :   name: 'Ran Nachmany', me: 'rannachmany', claim: 'Android Google Developer Expert'
    'angularjs':  name: 'Matias Niemelä', me: 'matsko', claim: 'AngularJS Core Team'
    'php':        name: 'Phil Sturgeon', me: 'philsturgeon', claim: 'PHP Top Answerer'
    'node.js':    name: 'Tim Caswell', me: 'creationix', claim: 'Early Node.js Contributor'
    'ios':        name: 'Wain Glaister', me: 'wain', claim: 'iOS Top Answerer'
    'asp.net':    name: 'Amir Rajan', me: 'amirrajan', claim: 'ASP .net AirPair Expert'
    'c++':        name: 'Steve Purves', me: 'stevejpurves', claim: 'C++ AirPair Expert'
    'c#':         name: 'John Feminella', me: 'john-feminella', claim: 'C# Top Answerer'
    'java':       name: 'Marko Topolnik', me: 'marko', claim: 'Java Top Answerer'
