module.exports =
  so10:
    'ruby':       name: 'Yehuda Katz', me: 'wycats', claim: 'Rails Core Team Member'
    'python':     name:'Daniel Roseman', me: 'danielroseman', claim: 'Djano #1 Answerer'
    'android' :   name:'Ran Nachmany', me: 'rannachmany', claim: 'Android Google Developer Expert'
    'angularjs':  name:'Matias Niemelä', me: 'matsko', claim: 'AngularJS Core Team'
    'php':        name:'Phil Sturgeon', me: 'philsturgeon', claim: 'PHP Top Answerer'
    'node.js':    name:'Tim Caswell', me: 'creationix', claim: 'Early Node.js Contributor'
    'ios':        name:'Wain Glaister', me: 'wain', claim: 'iOS Top Answerer'
    'asp.net':    name:'Amir Rajan', me: 'amirrajan', claim: 'ASP .net AirPair Expert'
    'c++':        name:'Steve Purves', me: 'stevejpurves', claim: 'C++ AirPair Expert'
    'c#':         name:'John Feminella', me: 'john-feminella', claim: 'C# Top Answerer'
    'java':       name: 'Marko Topolnik', me: 'marko', claim: 'Java Top Answerer'

  so15:
    'jquery':     name: 'Yehuda Katz', me: 'wycats', claim: 'Rails Core Team Member'
    'python':     name: 'Martijn Pieters', me: 'zopatista', claim: 'All time #1 Python Answerer'

  speakers:

    'danielroseman':  d: 'Fri, 1st Aug 16:00 GMT', n: 'Daniel Roseman', t: "What's New <br />in Django 1.7", so: '104349/daniel-roseman', tags: ['django'], u: 'danielroseman', g: '0f4cefeedec5163556751d61625eedd0', a: "All time Django #1 Answerer on stackoverflow - Daniel Roseman - will you taking you through the latest Django features in Django 1.7. Daniel will be covering advise on migration gotchas and finish off with a hint at 1.8."
    'ryanbigg':       d: 'Mon, 4th Aug 22:00 GMT', n: 'Ryan Bigg', t: "Refactoring Big Features <br />in Large Codebases", so: '15245/ryan-bigg', tags: ['rails','spree'], u: 'ryanbigg', g: '9a2a53db8e9b4476038c94a64b32833f', a: "Spree had a problem: the adjustments system was slow and difficult to understand. Over a period of some months, we refactored the code to be much faster and cleaner. The talk will cover the unique challenges that faced Spree and how we overcome them."
    'abedra':         d: 'Thu, 5th Aug 16:00 GMT', n: 'Aaron Bedra', t: "Creating Dynamic Security Controls With Repsheet", tw: 'abedra', tags: ['repsheet','rails','mod-security'], u: 'abedra', g: '24659470071279a42020d5b87411598e', a: "Description coming soon."
    'alyssa':         d: 'Thu, 7th Aug 17:00 GMT', n: 'Alyssa Reese', t: "Much A Do About UX <br />(for Developers)", tw: 'aareese', tags: ['ux'], u: 'alyssa', g: '98123d1387d7a27bc69933bfe5fc7967', a: "Alyssa has worked on UI/UX designs for over 40 startup & enterprise companies through several agencies, including her own. Alyssa will be talking exploring many of the pitfalls ambitious developers can fall in when deciding to create UX on the fly."
    'adymo':          d: 'Tue, 12th Aug 23:00 GMT', n: 'Alexander Dymo', t: "Rails Performance<br />Q & A", in: 'sy5n2q8o2i49/1KB9BDtDYm', tags: ['rails'], u: 'adymo', g: '990f1e2f3c6871d4305d3a316902b1bf', a: "Alexander is an entrepreneur, Y Combinator alum and Rails Performance Junky. He has 9 years of experience of Rails application development and performance optimization. In 2014 Alex has talked at conference and published various articles on the subject of Rails performance and is open for a 2 hour Q&A."
    'matsko':         d: 'Wed, 13th Aug 04:00 GMT', n: 'Matias Niemelä', t: "Awesome Interfaces with AngularJS Animations", gh: 'matsko', tags: ['anguarljs','ng-animate'], u: 'matsko', g: '3c0ca2c60c5cc418c6b3dbed47b23b69', a: "Description coming soon"
    'searls':         d: 'Sat, 16th Aug 22:00 GMT', n: 'Justin Searls', t: "The 'Rails of JavaScript' won't be a Framework", tw: 'searls', tags: ['rails'], u: 'searls', g: 'e6c6e133e74c3b83f04d2861deaa1c20', a: "The failure of Rails has been its perception as 'best web framework ever' instead of 'best web framework for apps like Basecamp'. Given that, it's clear why Rails makes writing a UI in HTML a joy but does few favors for JavaScript-heavy apps. We'll show how with Lineman.js & tools extracted find JavaScript joy!"
    'evgenyz':        d: 'Tue, 19th Aug 17:00 GMT', n: 'Evgeny Zislis', t: "Infrastructure as Code <br />Test Driven Chef", in: 'sy5n2q8o2i49/9ZPSg_JcCY', tags: ['chef'], u: 'evgenyz', g: '35d78874c6ba5c64db3256f6868515dc', a: "Every second company now uses Puppet or Chef. But very few apply similar testing discipline to infrastructure as application code. In just over an hour you will learn the various ways of writing tests when using Chef."
    'acuppy':         d: 'Wed, 20th Aug 17:00 GMT', n: 'Adam Cuppy', t: "Taming Chaotic Specs: <br />RSpec Design Patterns", in: 'sy5n2q8o2i49/OfJ8u7KW5E', tags: ['rails','rspec'], u: 'acuppy', g: '02bea4b58d39ba964c32c1609c728c53', a: "Hate when testing takes 3x as long because your specs are hard to understand? Following a few simple patterns, you can easily take a bloated spec and make it readable, DRY and simple to extend. This workshop is a refactor kata taking a bloated sample spec and making it manageable, readable and concise."
    'basarat':        d: 'Fri, 22th Aug 22:00 GMT', n: 'Basarat Ali', t: "<code>this</code> & Prototypal Inheritance<br /> in JavaScript", so: '390330/basarat', tags: ['javascript'], u: 'basarat', g: '1400be56ff17549b926dd3260da4a494', a: "No part of JavaScript is more misunderstood than its Prototypal inheritance. This presentation explains the behavior and usefulness of <code>this</code> and continues on to simplify Prototypal inheritance for the masses."
    'urish':          d: 'Mon, 25th Aug 17:00 GMT', n: 'Uri Shaked', t: "Avoiding Common Pitfalls <br />in Angular.JS", in: 'sy5n2q8o2i49/H_-Va_zs6e', tags: ['angularjs'], u: 'urish', g: '11696d5a1b7da83ebdf9c54a5dbd8f7a', a: "The things I wish someone told me when I started developing with Angular.JS. We will explore the Best practices as well Anti-Patterns every Angular.JS developer should be aware of."
    '2upmedia':       d: 'Tue, 26th Aug 18:00 GMT', n: 'Jorge Colon', t: "Emulate your staging server w <br />Vagrant, CentOS & LAMP", in: 'sy5n2q8o2i49/cPXFL7mBie', tags: ['vagrant','centos','lamp'], u: '2upmedia', g: 'b93914137ae67057880798210dc80e20', a: "Some developers still use FTP and a live server, some have graduated to running a development environment locally, but the savvy emulate the live server locally with a virtual server. Vagrant makes this so easy. We'll go through how to install Vagrant, configuring a basic Vagrant configuration, then install LAMP on CentOS."
    'joshowens':      d: 'Thu, 27th Aug 16:00 GMT', n: 'Josh Owens', t: "MeteorJS<br />1.0", tw: 'joshowens', tags: ['meteor'], u: 'joshowens', g: '089ddf30c09022b92363dd0d8ce2bdfd', a: "Description coming soon."
    'auser':          d: 'Thu, 28th Aug 16:00 GMT', n: 'Ari Lerner', t: "Robotics powering interfaces <br />with AngularJS", u: 'auser', gh: 'auser', tags: ['angularjs'], g: '0ec7fe2c17900b71bd85ff63fc9d8a17', a: "Ari is a co-author of The Rails 4 Way, Riding Rails with AngularJS and the Beginner’s Guide to AngularJS. Recently Ari has been training folks in AngularJS at Hack Reactor as a JavaScript teacher. Ari also publishes ng-newsletter.com."
    'mariovisic':     d: 'Fri, 29th Aug 22:00 GMT', n: 'Mario Visic', t: "ActiveRecord without ActiveRecord", u: 'mariovisic', tw: 'mariovisic', tags: ['rails','activerecord'], g: 'db58858a009745e96871e04ef497269a', a: "Description coming soon"
    'u':              d: '', n: '', t: "", in: '', tags: [''], u: '', g: '', a: ""
