module.exports =
  ApiConfig: require './../models/ApiConfig'
  Company: require './../models/company'
  Expert: require './../models/expert'
  Index: require './index'
  MarketingTag: require './marketingtag'
  Message: require './message'
  Order: require './order'
  PayMethod: require './payMethod'
  Request: require './request'
  Room: require './room'
  Settings: require './settings'
  Tag: require './tag'
  User: require './../models/user'
