describe "Server-side suite", ->
  describe 'api/companys', (done) -> require './api/companys'
  describe 'api/experts', (done) -> require './api/experts'
  describe 'api/orders', (done) -> require './api/orders'
  describe 'api/requests', (done) -> require './api/requests'
  describe 'mail/mailman', (done) -> require './mail/mailman'
  describe 'mix/tags', (done) -> require './mix/tags'
  describe 'services/autoMatchSpec', (done) -> require './services/autoMatchSpec'
  describe 'services/experts', (done) -> require './services/experts'
  describe 'services/orders', (done) -> require './services/orders'
  describe 'services/rates', (done) -> require './services/paypal-adaptive'
  describe 'services/rates', (done) -> require './services/rates'
  describe 'services/request', (done) -> require './services/request'
  describe 'services/requestCalls', (done) -> require './services/requestCalls'
